[sidebar]
emoji = "ğŸ£"
subtitle = "å°‘ã—ãšã¤æˆé•·ã—ã¦è‡ªåˆ†ã‹ã‚‰è¦‹ãˆã‚‹ä¸–ç•Œã‚’ãƒ¯ã‚¯ãƒ¯ã‚¯ã§ãã‚‹ä¸–ç•Œã«"

[sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.jpg'

## Widgets
[[widgets.page]]
type = "toc"
