baseURL = 'https://snyt45.com/'
languageCode = 'ja'
title = 'Small Changes'
copyright = 'snyt45'

[module]
  [[module.imports]]
    path = 'github.com/CaiJimmy/hugo-theme-stack/v3'

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/snyt45"

[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/snyt45"

[menu.social.params]
icon = "brand-twitter"

[params.sidebar]
emoji = "ğŸ£"
subtitle = "å°‘ã—ãšã¤æˆé•·ã—ã¦è‡ªåˆ†ã‹ã‚‰è¦‹ãˆã‚‹ä¸–ç•Œã‚’ãƒ¯ã‚¯ãƒ¯ã‚¯ã§ãã‚‹ä¸–ç•Œã«"

[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.jpg'
