baseURL = 'https://snyt45.com/'
languageCode = 'ja'
title = 'Small Changes'
copyright = 'snyt45'

[module]
  [[module.imports]]
    path = 'github.com/CaiJimmy/hugo-theme-stack/v3'

[params.sidebar]
emoji = "ğŸ£"
subtitle = "å°‘ã—ãšã¤æˆé•·ã—ã¦è‡ªåˆ†ã‹ã‚‰è¦‹ãˆã‚‹ä¸–ç•Œã‚’ãƒ¯ã‚¯ãƒ¯ã‚¯ã§ãã‚‹ä¸–ç•Œã«"

[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.jpg'
